### PR TITLE
Ruby 3 support

### PR DESCRIPTION
**Pull request by krisleech**
fixed up version of https://github.com/krisleech/wisper/pull/197 to prepare for release

### CODE REVIEW

**Comment by krisleech** [comment]
@doit @jstoks @merringtion @thirunjuguna 

I branched off https://github.com/krisleech/wisper/pull/197 and created a new PR, rebased on `main`, fixed the conflicts and squashed the commits to tidy up the history.

I've added @jstoks @merringtion @thirunjuguna as co-authors and @doits is the author to the original commit. Hope that is okay, did I miss anyone?

Any final comments/feedback before I prepare a release candidate after merging and then a 3.0 release.

**Comment by patrickemuller** [comment]
@krisleech kudos to you buddy, what a great work!

**Review by patrickemuller — APPROVED** [review]
🚀

**Comment by synth** [comment]
Thank you for this update! One friendly request is to update the VERSION file. On the master branch it is still 2.0.x even though the commit has been tagged in Github as an 3.x.x.rc already. I think this would allow easier version control in our Gemfiles. For instance, right now, I can't do: 

```
gem 'wisper', '~> 3.0.0.rc1', github: 'krisleech/wisper'
```

because it doesn't know about it. 

I can do this: 
```
gem 'wisper', github: 'krisleech/wisper', branch: 'master'

# or

gem 'wisper', github: 'krisleech/wisper', tag: 'v3.0.0.rc1'
```

I think the former is preferred though. Thank you!

**Pull request merged**
