### PR TITLE
Add setting for Registration::Object default prefix

### PR DESCRIPTION
**Pull request by nepalez**
Hi, Kris!

I've tried to add configuration setting to Wisper::Configuration to make
it possible changing default prefix of Registration::Object.

To prevent the Object class from messing by the default setter, I've extracted
the Prefix as value object. Then I've added a method to the Configuration,
because it seems the better solution, than accessing the internal class directly.

I've split changes to 3 commits for every single step of my refactoring.

I didn't discussed it in advance, 'cause it turned out to be fast and simple.
If you find it appropriate, please accept the commits.

### CODE REVIEW

**Comment by krisleech** [comment]
In principle I'm happy with this, thanks :smile: I'll take a closer look as soon as possible. There is one failure on ruby-head. Would you take a look please?

**Comment by nepalez** [comment]
D'oh! This was due to inaccurate insulation of my specs from each other.
Corrected.

**Comment by nepalez** [comment]
And one more little thing.

I've noticed the list of events can be set as "strict" String, Symbol, Array,
or Regex only.

For example, when I use not a String, but its subling, I raise ArgumentError:

```ruby
Event = Class.new(String)
event = Event.new "foo"

event.is_a? String # => true
event # => "foo"

BlockRegistration.broadcast event, #...
# => ArgumentError "Event not supported for `on` argument"
```

This is because `Registration#should_broadcast?` checks the class name directly,
via `class.name`, not `is_a?` or `is_kind_of?`.

And once again, before solving the problem I've isolated Events as a
value object quacking like an array in responce to #include?.

I didn't figure out yet how to made my change
(use `is_a?` instead of `class.name`) to be well-written,
so I postponed it for a while.

But IMHO the extraction makes Wisper::Registration more readable and testable,
so is could make sense by itself.

**Comment by krisleech** [comment]
I've not forgot about this.

**Comment by krisleech** [comment]
Thanks and sorry for the delay!

**Comment by krisleech** [comment]
Does this need something adding to the README? Thanks.

**Pull request merged**
