### PR TITLE
Fix issue with logger on hash arguments

### PR DESCRIPTION
**Pull request by smostovoy**
Spec and a fix for https://github.com/krisleech/wisper/issues/134

### CODE REVIEW

**Comment by krisleech** [comment]
Thanks for the spec, much more helpful than just a bug report.

Do you fancy having a go at the implementation?

It looks like the issue is because the `object` `responds_to?(:key)` but `key` requires some arguments so in all likelyhood `key`, in the case, isn't returning an id. 

So we need to check the arity of the method first to make sure it has an arity of 0 (i.e. takes no arguments). You can do this with the `method` method. http://ruby-doc.org/core-1.9.3/Method.html

**Comment by smostovoy** [comment]
yeah, `key` is the problem. It was a bit unclear for me what is the idea behind using it because for Hash I would expect full inspect with values

**Comment by smostovoy** [comment]
Just FYI, to fix it locally in rails I made it like this 

```ruby
  def arg_names(args)
    return 'no arguments' if args.empty?
    args.map { |arg| arg.try(:to_global_id).try(:to_s) || arg.inspect }.join(', ')
  end
```

**Comment by krisleech** [comment]
`key` is checked because it is a common name for a method which returns an identifier for an object, it checks for `id`, then  `uuid`, then `key` and finally falls back to `object_id`. However in the case of a Hash `key` doesn't return an identifier. Check the stacktrace of the failing spec and you will see it points to [here](https://github.com/krisleech/wisper/blob/master/lib/wisper/broadcasters/logger_broadcaster.rb#L20). As soon as we do `send(:key)` we get an error because `Hash.key` accepts an argument, it isn't what we expect.

Your snippet fixes it because it no longer calls the `name` which is where the error is raised. However `to_global_id` is ActiveJob specific so not suitable for inclusion in Wisper which is Ruby-only.

**Comment by smostovoy** [comment]
yeah, I understood the priority thing. Just didn't got why `key` is in stack. Using GID if available is a good way imho. Also, having values in log for Array and Hash arguments is valuable. If you agree I'll implement those things

**Comment by smostovoy** [comment]
I won't use rails` `:try` of course

**Comment by smostovoy** [comment]
ah, actually `name` get a similar GID thing, so it's just about adding values

**Comment by smostovoy** [comment]
looks good now?

**Comment by krisleech** [comment]
Looks good :) Can you add an entry to [CHANGELOG](https://github.com/krisleech/wisper/blob/master/CHANGELOG.md) please, add a new heading above `# 2.0.0-rc1` called `# HEAD (unreleased)` and add yourself as an author and a bullet point to describe what this PR fixes. Thanks.

**Comment by smostovoy** [comment]
done

**Comment by krisleech** [comment]
👍  merged.

**Pull request merged**
