### PR TITLE
Upgrade to RSpec latest

### PR DESCRIPTION
**Pull request by adomokos**
I noticed this warning when I ran the specs:

wisper-warning

Upgrading to the latest version of RSpec fixes that warning.

### CODE REVIEW

**Comment by krisleech** [comment]
:+1: Looks like it fails on Ruby and JRuby HEAD, not sure why (might be something to do with RSpec itself). Any chance you could take a look?

**Comment by adomokos** [comment]
I narrowed down the root cause to be an older version of bundler on Travis CI. I installed the 2.4.0-dev version of Ruby and used the same version of bundler locally to replicate the error.

This is the bundler version on Travis: `Bundler version 1.6.9`
I [added](https://github.com/krisleech/wisper/pull/131/commits/424766557105bb2bafbb4fc395f9900721f72a7c) a `before_install` step to `.travis.yml` to upgrade bundler with no luck. :-(

Sorry, I don't have more time to iron out this issue. I am OK with closing it without merging.

Thanks!

**Comment by krisleech** [comment]
Thanks for looking in to it. I grabbed your branch and added `bundle --version` so we can see the version being used and it looks like it does use a newer version, `10.11`, but not for the failing rubies.

```
$ gem update bundler
Updating installed gems
Nothing to update
$ bundle --version
Bundler version 1.6.9
```

I also have no idea why.

**Comment by krisleech** [comment]
Okay a small amount of progress: https://travis-ci.org/krisleech/wisper/builds/118191563

I changed `gem update bundler` to `gem install bundler` and it fixes all but ruby-head. Don't ask me why this makes any difference :smile:

**Comment by krisleech** [comment]
On ruby-head:

```
$ gem install bundler
Fetching: bundler-1.11.2.gem (100%)
Successfully installed bundler-1.11.2
1 gem installed

$ bundle --version
Bundler version 1.6.9
```

It doesn't look like Travis are going to fix it either: https://github.com/travis-ci/travis-ci/issues/3531

**Comment by krisleech** [comment]
Looks like a Ruby/Rubygems bug https://github.com/travis-ci/travis-ci/issues/5798

I'll leave this open until they fix it, then we can restart the build and hope for green.

**Comment by adomokos** [comment]
Sounds good, thanks for looking into it @krisleech!

**Comment by krisleech** [comment]
They have fixed the above issues and ruby-head is now passing, unfortunately it looks like there is a new issue with jruby-head now.

* https://github.com/travis-ci/travis-ci/issues/5861

Waiting for a fix.

**Comment by krisleech** [comment]
It seems Travis aren't in a hurry to fix this issue.

I fixed `allowed_failures` for Travis on master branch. If you rebase and force push, or merge in master and push, Travis should now pass.

**Comment by krisleech** [comment]
merged, thanks 👍

**Pull request merged**
