### PR TITLE
Support broadcasting at the class level

### PR DESCRIPTION
**Pull request by jackcasey**
I wanted this behaviour for myself to structure one service listening to events from another, without instances in the mix. 

Let me know if there is anything I can do to make it more useful for others or more suitable for merging.

Thanks for the gem!

### CODE REVIEW

**Comment by carlshimer** [comment]
I am looking forward to this feature.  was just going to write it but then found this PR

**Comment by krisleech** [comment]
I'll have a think about this if you don't mind. Thanks.

**Comment by mezis** [comment]
@jackcasey, @carlshimer: Do we need this behaviour by default in the gem? I mean, you can already `extend Wisper::Publisher` in your class to have class-level publication?

**Comment by jackcasey** [comment]
I didn't know about or think about extending Wisper::Publisher. If that does the job I'm happy to close this.

**Comment by krisleech** [comment]
@mezis good call.

@jackcasey this works:

```ruby
class Foo
  extend Wisper::Publisher

  def self.call
    broadcast(:yep)
  end
end

class Bar
  def on_yep
    puts "YEP"
  end
end

Foo.subscribe(Bar.new, prefix: 'on')
Foo.call
YEP
```

Might be worth adding a sentence to the README, or wiki, about this.

**Pull request closed without merging**
